# Build stage
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /dns-api ./cmd/api

# Final stage
FROM alpine:latest
WORKDIR /
COPY --from=builder /dns-api /dns-api
EXPOSE 8080
CMD ["/dns-api"]

