package http

import (
	"internal-dns/configs"
	"internal-dns/internal/domain"
	"internal-dns/internal/infrastructure/transport/http/middleware"
	"internal-dns/internal/repository"
	"internal-dns/internal/usecase"
	"internal-dns/pkg/token"

	"github.com/labstack/echo-contrib/prometheus"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "internal-dns/docs" // docs is generated by Swag CLI
)

func RegisterRoutes(e *echo.Echo, cfg *configs.Config, authUC usecase.AuthUseCase, userUC usecase.UserUseCase, dnsUC usecase.DNSRecordUseCase, userRepo repository.UserRepository, tokenGenerator token.Generator) {
	// Prometheus Middleware
	p := prometheus.NewPrometheus("echo", nil)
	p.Use(e)

	// Health Check
	healthHandler := NewHealthHandler()
	e.GET("/api/v1/health", healthHandler.HealthCheck)

	// Swagger
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// Rate Limiter
	rateLimiterConfig := middleware.RateLimiterConfig{
		Enabled: cfg.RATE_LIMITER_ENABLED,
		RPS:     cfg.RATE_LIMITER_RPS,
		Burst:   cfg.RATE_LIMITER_BURST,
		TTL:     cfg.RATE_LIMITER_TTL,
	}
	e.Use(middleware.RateLimiter(rateLimiterConfig))

	// Handlers
	authHandler := NewAuthHandler(authUC)
	userHandler := NewUserHandler(userUC)
	dnsRecordHandler := NewDNSRecordHandler(dnsUC) // Renamed for consistency

	// JWT Middleware
	jwtMiddleware := middleware.NewJWTMiddleware(tokenGenerator, userRepo)

	// Group routes
	v1 := e.Group("/api/v1")

	// Auth routes
	authGroup := v1.Group("/auth")
	{
		authGroup.POST("/register", authHandler.Register)
		authGroup.POST("/login", authHandler.Login)
	}

	// Admin routes
	adminGroup := v1.Group("/admin")
	adminGroup.Use(jwtMiddleware.Auth(domain.RoleAdmin))
	{
		adminGroup.GET("/users", userHandler.ListUsers)
		adminGroup.GET("/users/:id", userHandler.GetUser)
		adminGroup.PUT("/users/:id/status", userHandler.UpdateUserStatus) // Changed PATCH to PUT
	}

	// DNS Record routes
	dnsGroup := v1.Group("/dns-records")
	dnsGroup.Use(jwtMiddleware.Auth(domain.RoleUser, domain.RoleAdmin))
	{
		dnsGroup.POST("", dnsRecordHandler.CreateRecord)
		dnsGroup.GET("", dnsRecordHandler.ListRecords)
		dnsGroup.GET("/:id", dnsRecordHandler.GetRecord)
		dnsGroup.PUT("/:id", dnsRecordHandler.UpdateRecord)
		dnsGroup.DELETE("/:id", dnsRecordHandler.DeleteRecord)
	}
}

